# Generated by Django 6.1 on 2026-08-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expiringtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomfile',
            name='encrypted_data',
            field=models.BinaryField(blank=True, help_text='Encrypted DICOM bytes stored directly in DB', null=True),
        ),
        migrations.AlterField(
            model_name='dicomfile',
            name='file_path',
            field=models.CharField(blank=True, help_text='Local file path (legacy, being phased out)', max_length=500),
        ),
    ]
